### ISSUE TITLE
Late packets should get NACK'ed

### ISSUE THREAD

**Issue by lthiery** [helium/virtual-lorawan-device#21]

**Comment by lthiery** [comment]
There are updates in semtech-udp that allow this and work is underway integrating the new version into the vld app.

**Comment by openxzx** [comment]
Hi, @lthiery. I would like to know when the newest version of semtech-udp can be supported into the vld app, thank you.

**Comment by lthiery** [comment]
@openxzx pls see #43

**Comment by openxzx** [comment]
@lthiery OK, thank you.

**Comment by lthiery** [comment]
The latest release (0.2.13) will now NACK late packets which makes use of the RX2 windows possible.
