### ISSUE TITLE
Error when attempting to run Docker

### ISSUE THREAD

**Issue by mjohngreene** [helium/virtual-lorawan-device#47]
After building the `virtual-lorawan-device:latest` container with `docker buildx build`, running it with `docker run virtual-lorawan-device:latest` generated the following error: `Error: Config(missing field 'device')`  I could not find "missing" anywhere in the repo, though.

Any ideas as to a potential source for this error and/or how to fix it?

**Comment by lthiery** [comment]
Perhaps you have not mounted the configuration file? The [readme show you how to do it with docker compose](https://github.com/helium/virtual-lorawan-device#example-docker-compose) but if you want to run by hand, you still need to give it your configuration file somehow.

**Comment by mjohngreene** [comment]
Thanks, @lthiery.  I had mistakenly read the README build instrux as either/or.  

I was able to build and run the container successfully using the `docker buildx` first to create the image and then running the `docker compose` with `- ./settings/settings.toml:/etc/virtual-lorawan-device/settings.toml` added to the example.  The virtual devices created are unable to join the virtual network, though, so I still have some troubleshooting to do.

**Comment by lthiery** [comment]
Closed due to inactivity
